services:
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:create_app()"
    envVars:
      - key: mysql://AcademyAwards_rhythmyou:ff3c6c4110d94b2975058fd7a25613ca907e1eec@14kzg.h.filess.io:61002/AcademyAwards_rhythmyou
        value: mysql://AcademyAwards_rhythmyou:ff3c6c4110d94b2975058fd7a25613ca907e1eec@14kzg.h.filess.io/AcademyAwards_rhythmyou
